// config/letterDefinitions.js
module.exports = [
  { letter: "A", count: 12, score: 1 },
  { letter: "B", count: 2, score: 3 },
  { letter: "C", count: 2, score: 4 },
  { letter: "Ç", count: 2, score: 4 },
  { letter: "D", count: 2, score: 3 },
  { letter: "E", count: 8, score: 1 },
  { letter: "F", count: 1, score: 7 },
  { letter: "G", count: 1, score: 5 },
  { letter: "Ğ", count: 1, score: 8 },
  { letter: "H", count: 1, score: 5 },
  { letter: "I", count: 4, score: 2 },
  { letter: "İ", count: 7, score: 1 },
  { letter: "J", count: 1, score: 10 },
  { letter: "K", count: 7, score: 1 },
  { letter: "L", count: 7, score: 1 },
  { letter: "M", count: 4, score: 2 },
  { letter: "N", count: 5, score: 1 },
  { letter: "O", count: 3, score: 1 },
  { letter: "Ö", count: 1, score: 7 },
  { letter: "P", count: 1, score: 5 },
  { letter: "R", count: 6, score: 1 },
  { letter: "S", count: 3, score: 2 },
  { letter: "Ş", count: 2, score: 4 },
  { letter: "T", count: 5, score: 1 },
  { letter: "U", count: 3, score: 2 },
  { letter: "Ü", count: 2, score: 3 },
  { letter: "V", count: 1, score: 7 },
  { letter: "Y", count: 2, score: 3 },
  { letter: "Z", count: 2, score: 4 },
  { letter: "*", count: 2, score: 0 },
];
